# Generated by Django 5.2.8 on 2025-12-09 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_selfie', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EmailCapture',
        ),
    ]
