# Generated by Django 6.0 on 2025-12-17 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selfie', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_base64', models.TextField(blank=True, help_text='Base64 kódolt kép', null=True)),
                ('image_file', models.ImageField(blank=True, null=True, upload_to='photos/%Y/%m/%d/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('photo_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='app_selfie.photosession')),
            ],
            options={
                'verbose_name': 'Fotó',
                'verbose_name_plural': 'Fotók',
                'ordering': ['-created_at'],
            },
        ),
    ]
