# Generated by Django 6.0 on 2026-01-07 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selfie', '0004_photo'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='uploaded_images/%Y/%m/%d/', verbose_name='Kép fájl')),
                ('description', models.TextField(blank=True, help_text='Opcionális leírás a képhez', null=True, verbose_name='Leírás')),
                ('is_active', models.BooleanField(default=True, help_text='A kép használható-e', verbose_name='Aktív')),
                ('upload_date', models.DateTimeField(auto_now_add=True, verbose_name='Feltöltés dátuma')),
            ],
            options={
                'verbose_name': 'Feltöltött kép',
                'verbose_name_plural': 'Feltöltött képek',
                'ordering': ['-upload_date'],
            },
        ),
    ]
