# Generated by Django 6.0.1 on 2026-01-08 13:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_selfie', '0005_uploadedimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='photosession',
            name='final_image',
            field=models.ImageField(blank=True, null=True, upload_to='final_photos/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='photosession',
            name='overlay_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='app_selfie.uploadedimage', verbose_name='Felhasznált overlay kép'),
        ),
    ]
